Adjust task names, tags and variables to the Adfinis standard
adfinis-sygroup/ansible-role-openshift_backup pull request #5
Opened 2018-09-26 18:31 UTC by karras

##### SUMMARY

Adjust task names, tags and variables to the Adfinis standard 

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
n/a
```

##### ADDITIONAL INFORMATION

```
n/a
```

2018-09-26 20:58 UTC, tongpu requested changes
LGTM besides the minor tag issue

2018-09-26 20:58 UTC, tongpu commented on tasks/main.yml
> +    - 'role::openshift_backup'
2nd line should probably be `role::openshift_backup:install`?

2018-09-27 08:37 UTC, karras commented
Fixed

2018-09-27 08:47 UTC, tongpu approved these changes
LGTM

2018-09-27 08:47 UTC, merged